### ISSUE TITLE
ALX programs are missing

### ISSUE THREAD

**Issue by ab-elhaddad** [Mahmoudgalalz/JuniorJobs#72]
ALX is an organization that aims to accelerate the careers of young Africans by providing world-class training. And they now offering multiple programs for free.
You can see the programs they are offering [here](https://www.alxafrica.com/programmes/).

**Comment by Mahmoudgalalz** [comment]
Hi @ab-elhaddad I would be happy if you worked on adding it
feel free to send your PR and ask me for reviewing it, and if you want some hints you can mention here in this issue

**Comment by ab-elhaddad** [comment]
Hi @Mahmoudgalalz, I would be more than happy to work on it.
It would be very helpful to tell from where I should start or to give me any tips you believe will be useful, that would be greatly appreciated.

**Comment by Mahmoudgalalz** [comment]
[Kick Off](../blob/main/src/components/programs/Programs.astro)
this is where you could start, append the program details into the array of object

the image should be hosted on something we would trust will rest for a long time, like an S3 link, a link from their website

it would be added to the items, make sure the scroll script is working properly
[Scroll](../blob/main/src/pages/programs.astro)

Also, consider you can't open the opportunities page, cuz it wants a DB connection, sorry it's forbidden for OSS

we will maintain it to be available on development without needing for env variables

**Comment by Mahmoudgalalz** [comment]
closed by this #75
